### ISSUE TITLE
How to implement new coin?

### ISSUE THREAD

**Issue by farsider350** [horizontalsystems/bank-wallet-android#546]
Is there a guide for implementing a coin into the code for a PR?

**Comment by abdrasulov** [comment]
Hello @farsider350. Thanks for your interest in contributing to our app. We're working on the guide for contributors as of now. We will let you know when it is ready.

**Comment by esengulov** [comment]
> Is there a guide for implementing a coin into the code for a PR?

If you're looking add ERC20 token into a Bank Wallet, here is the repository for that https://github.com/horizontalsystems/Supported-ERC20-Tokens

If you refer to other blockchains/currencies (Monero, Dash, LTC etc) then at this point we are integrating decentralized support for each blockchain separately and it's a major task on its own. 

At this point the BANK supports decentralize integration for Bitcoin, Bitcoin Cash and Ethereum blockchains. The support for DASH blockchain is currently in progress and likely to take another 3-4 months. Can't comment on any other blockchains besides that because we are not yet set on the priority level for each blockchain when it comes to choose which one will be integrated next.

**Comment by farsider350** [comment]
Appreciate it. Thank you..
